# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Feijoa and a Cuppa Tea"
description: > # this means to ignore newlines until "email:"
   Some personal ramblings on tabi

email: feijoaandacuppatea@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Ting'
author: 'Ting'
author_image: "/assets/images/ting.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options

